package com.empcontrol.agent.net;
import com.empcontrol.agent.config.AgentIdentity; import com.empcontrol.agent.security.*; import com.google.gson.*; import org.bukkit.Bukkit; import org.bukkit.plugin.Plugin; import org.java_websocket.client.WebSocketClient; import org.java_websocket.handshake.ServerHandshake; import java.net.*; import java.net.http.*; import java.time.Duration; import java.util.*; import java.util.concurrent.*;
public final class AgentClient { private final Plugin plugin; private final Gson gson=new Gson(); private final Queue<String> queue=new ConcurrentLinkedQueue<>(); private final ReplayGuard replay=new ReplayGuard(); private final Set<String> executedCommands=Collections.synchronizedSet(new HashSet<>()); private AgentIdentity identity; private WebSocketClient ws; private int reconnects, failed; public AgentClient(Plugin plugin){this.plugin=plugin;} public boolean connected(){return ws!=null && ws.isOpen();} public int reconnects(){return reconnects;} public int queueSize(){return queue.size();} public int failed(){return failed;}
  public AgentIdentity pair(String apiBase, String token) throws Exception { String publicId=UUID.randomUUID().toString(); Map<String,Object> body=Map.of("pairingToken",token,"publicIdentity",publicId,"serverInfo",Map.of("version",Bukkit.getVersion(),"address",Bukkit.getServer().getIp()+":"+Bukkit.getPort())); HttpRequest req=HttpRequest.newBuilder(URI.create(apiBase+"/agent/pair")).timeout(Duration.ofSeconds(15)).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(gson.toJson(body))).build(); HttpResponse<String> res=HttpClient.newHttpClient().send(req,HttpResponse.BodyHandlers.ofString()); if(res.statusCode()>=300) throw new IllegalStateException(res.body()); JsonObject obj=JsonParser.parseString(res.body()).getAsJsonObject(); identity=new AgentIdentity(obj.get("serverId").getAsString(), obj.get("agentSecret").getAsString(), apiBase, obj.get("websocketUrl").getAsString(), publicId); connect(identity); return identity; }
  public void connect(AgentIdentity id){ identity=id; try { URI base=URI.create(id.apiBaseUrl()); String scheme=base.getScheme().equals("https")?"wss":"ws"; URI uri=URI.create(scheme+"://"+base.getAuthority()+id.websocketPath()+"?serverId="+URLEncoder.encode(id.serverId(), java.nio.charset.StandardCharsets.UTF_8)+"&identity="+URLEncoder.encode(id.publicIdentity(), java.nio.charset.StandardCharsets.UTF_8)); ws=new WebSocketClient(uri){ public void onOpen(ServerHandshake h){ flush(); } public void onMessage(String m){ handle(m); } public void onClose(int c,String r,boolean remote){ reconnects++; Bukkit.getScheduler().runTaskLaterAsynchronously(plugin, () -> connect(identity), 100L); } public void onError(Exception ex){ failed++; plugin.getLogger().warning("EMP websocket error: "+ex.getMessage()); } }; ws.connect(); } catch(Exception e){ failed++; plugin.getLogger().warning("EMP connect failed: "+e.getMessage()); } }
  public void send(String type, Object payload){ if(identity==null) return; String nonce=UUID.randomUUID().toString(); long ts=System.currentTimeMillis(); String json=gson.toJson(payload); String secret=MessageSigner.derivedSecret(identity.agentSecret()); String sig=MessageSigner.sign(secret, identity.serverId()+"."+ts+"."+nonce+"."+json); String msg=gson.toJson(Map.of("type",type,"serverId",identity.serverId(),"timestamp",ts,"nonce",nonce,"payload",payload,"signature",sig)); if(connected()) ws.send(msg); else if(queue.size()<250) queue.add(msg); else failed++; }
  private void flush(){ String m; while((m=queue.poll())!=null && connected()) ws.send(m); }
  private void handle(String raw){ JsonObject obj=JsonParser.parseString(raw).getAsJsonObject(); if(!"remoteCommand".equals(obj.get("type").getAsString())) return; String serverId=obj.get("serverId").getAsString(), nonce=obj.get("nonce").getAsString(); long ts=obj.get("timestamp").getAsLong(); JsonElement payload=obj.get("payload"); if(identity==null || !identity.serverId().equals(serverId) || Math.abs(System.currentTimeMillis()-ts)>60000 || !replay.accept(nonce)) return; String secret=MessageSigner.derivedSecret(identity.agentSecret()); String canonical=serverId+"."+ts+"."+nonce+"."+gson.toJson(payload); if(!MessageSigner.sign(secret, canonical).equals(obj.get("signature").getAsString())) return; String command=payload.getAsJsonObject().get("command").getAsString(); String commandId=payload.getAsJsonObject().get("commandId").getAsString(); if(!executedCommands.add(commandId)) return; Bukkit.getScheduler().runTask(plugin, () -> { boolean ok=Bukkit.dispatchCommand(Bukkit.getConsoleSender(), command); send("remoteCommandResult", Map.of("commandId",commandId,"success",ok,"result", ok?"Dispatched to Bukkit console":"Bukkit rejected command")); }); }
}
