services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: emp_control
      POSTGRES_USER: emp
      POSTGRES_PASSWORD: emp_dev_password
    ports:
      - "5432:5432"
    volumes:
      - emp-postgres:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
volumes:
  emp-postgres:
