import { z } from 'zod';
import type { FastifyInstance } from 'fastify';
import { prisma } from '../plugins/prisma.js';
import { audit } from '../services/audit.js';
import { randomToken, sha256 } from '../utils/crypto.js';
import { env } from '../config/env.js';

const serverSchema = z.object({ displayName: z.string().min(1), type: z.enum(['PAPER', 'VELOCITY', 'OTHER']).default('PAPER'), address: z.string().optional() });
export async function serverRoutes(app: FastifyInstance) {
  app.get('/servers', { preHandler: app.requireRole('VIEWER') }, async (req) => ({ servers: await prisma.server.findMany({ where: { workspaceId: req.userContext!.workspaceId }, include: { latestSnapshot: true, alerts: { orderBy: { createdAt: 'desc' }, take: 1 } }, orderBy: { createdAt: 'desc' } }) }));
  app.post('/servers', { preHandler: app.requireRole('OWNER') }, async (req) => { const body = serverSchema.parse(req.body); const server = await prisma.server.create({ data: { workspaceId: req.userContext!.workspaceId, ...body } }); await seedPolicies(server.id); await audit({ userId: req.userContext!.id, serverId: server.id, action: 'server.create' }); return { server }; });
  app.get('/servers/:id', { preHandler: app.requireRole('VIEWER') }, async (req) => ({ server: await getServer(req) }));
  app.patch('/servers/:id', { preHandler: app.requireRole('OWNER') }, async (req) => { const { id } = z.object({ id: z.string() }).parse(req.params); const body = serverSchema.partial().parse(req.body); await prisma.server.findFirstOrThrow({ where: { id, workspaceId: req.userContext!.workspaceId } }); const server = await prisma.server.update({ where: { id }, data: body }); await audit({ userId: req.userContext!.id, serverId: id, action: 'server.update' }); return { server }; });
  app.delete('/servers/:id', { preHandler: app.requireRole('OWNER') }, async (req) => { const { id } = z.object({ id: z.string() }).parse(req.params); await prisma.server.findFirstOrThrow({ where: { id, workspaceId: req.userContext!.workspaceId } }); await prisma.server.delete({ where: { id } }); await audit({ userId: req.userContext!.id, serverId: id, action: 'server.delete' }); return { ok: true }; });
  app.post('/servers/:id/pairing-token', { preHandler: app.requireRole('OWNER') }, async (req) => { const server = await getServer(req); const token = randomToken(32); await prisma.agentCredential.create({ data: { serverId: server.id, publicIdentity: `pending-${randomToken(8)}`, secretHash: 'pending', pairingTokenHash: sha256(token), pairingExpiresAt: new Date(Date.now() + env.AGENT_PAIRING_TOKEN_TTL_MINUTES * 60_000) } }); await audit({ userId: req.userContext!.id, serverId: server.id, action: 'agent.pairing_token' }); return { pairingToken: token, expiresInMinutes: env.AGENT_PAIRING_TOKEN_TTL_MINUTES }; });
  app.post('/servers/:id/revoke-agent', { preHandler: app.requireRole('OWNER') }, async (req) => { const server = await getServer(req); await prisma.agentCredential.updateMany({ where: { serverId: server.id, revokedAt: null }, data: { revokedAt: new Date() } }); await prisma.server.update({ where: { id: server.id }, data: { status: 'OFFLINE' } }); await audit({ userId: req.userContext!.id, serverId: server.id, action: 'agent.revoke' }); return { ok: true }; });
  app.get('/servers/:id/metrics/latest', { preHandler: app.requireRole('VIEWER') }, async (req) => ({ latest: await prisma.serverLatestSnapshot.findUnique({ where: { serverId: (await getServer(req)).id } }) }));
  app.get('/servers/:id/metrics/history', { preHandler: app.requireRole('STAFF') }, async (req) => ({ metrics: await prisma.serverMetric.findMany({ where: { serverId: (await getServer(req)).id }, orderBy: { createdAt: 'desc' }, take: 100 }) }));
}
async function getServer(req: any) { const { id } = z.object({ id: z.string() }).parse(req.params); return prisma.server.findFirstOrThrow({ where: { id, workspaceId: req.userContext.workspaceId } }); }
async function seedPolicies(serverId: string) { for (const command of ['op','deop','stop','restart','reload','rl','plugins','pl','ver','version','luckperms','lp','pex','permissions','gamemode','give','effect','whitelist off','pardon','ban','unban','plugman']) await prisma.commandPolicy.upsert({ where: { serverId_command: { serverId, command } }, update: {}, create: { serverId, command, action: ['op','deop','stop'].includes(command) ? 'REQUIRE_CONFIRMATION' : 'ALERT_ONLY' } }); }
